### ISSUE TITLE
你这属于伪开源吗？

### ISSUE THREAD

**Issue by gotounix** [wangy8961/python3-concurrency-pics-02#2]
代码文件里面没有代码，查看代码要去网站，到了网站竟然还要注册……
CSDN这招学的还挺好，厉害！

**Comment by wangy8961** [comment]
请问我这个代码库有声明使用哪个开源协议吗？将代码放到 github 并不就是开源了，我还有私有库呢，我的劳动成果没必要共享给你，不喜欢可以无视即可

**Comment by gotounix** [comment]
PS：你的代码并没有放到 GitHub。
